import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

# font configuration nerd fonts
font:
  normal:
    family: "Fira Code Nerd Font"
    style: Regular
  bold:
    family: "Fira Code Nerd Font"
    style: Bold
  italic:
    family: "Fira Code Nerd Font"
    style: Italic

# padding
padding:
  x: 10
  y: 10
